### ISSUE TITLE
ask for a help

### ISSUE THREAD

**Issue by e665107** [TECREA/QuarkTS#12]
dear friend:
         Can you tell me this rtos will consume how much resources, when it runs on the stm8, or pic, or avr? I am looking for a minirtos, which can work well on this environment! osa is  a  good choice, but nonone mend it!

**Comment by kmilo17pet** [comment]
On STM8, AVR and 16/32-bit PIC, can take from 3.5 to 6 Kb of Program Memory and requires one hardware timer. Some configurations can be tunned to decrease the memory usage.
On 8bit PIC devices, the OS cannot build due the compiler limitations.
Take a look to the user manual.

I cannot recommend OSA because I have never used it, however, if that OS meets your needs, use it.

Best
